#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Christ Days Calendar Reminder Builder
Version 0.1.0 — 25 May 2026
Created by NemesisC64 for Lexmilian de Mello / Percarus.

This app parses Jesus_Centred_Christian_Holiday_Guide_2026.txt and the numbered
high-resolution banners in "High Res Banners for Days of Christ". It generates
calendar-safe .ics files with eight-day reminder alarms and unique UIDs so the
matching cancellation file targets only events created by this app.
"""

from __future__ import annotations

import datetime as dt
import json
import math
import os
import re
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

try:
    import tkinter as tk
    from tkinter import filedialog, messagebox, ttk
except Exception as exc:  # pragma: no cover
    raise SystemExit("Tkinter is required to run this desktop app.") from exc

APP_NAME = "Christ Days Calendar Reminder Builder"
APP_VERSION = "0.1.0"
APP_DATE = "25 May 2026"
APP_SIGNATURE = "NemesisC64 × Lexmilian de Mello / Percarus"
EVENT_UID_DOMAIN = "percarus-christ-days.local"
EVENT_UID_PREFIX = "percarus-christ-days"
DEFAULT_NOTICE_DAYS = 8
DEFAULT_START_YEAR = 2026
DEFAULT_END_YEAR = 2040

GOLD = "#d8b15e"
SOFT_GOLD = "#f2d793"
BG = "#090b12"
PANEL = "#111621"
PANEL2 = "#171c28"
TEXT = "#f7efd8"
MUTED = "#b6a777"
ERROR = "#ffb4a6"

HOLIDAY_TITLES = {
    1: "Advent",
    2: "Annunciation",
    3: "Christmas",
    4: "Holy Name of Jesus",
    5: "Epiphany",
    6: "Baptism of the Lord",
    7: "Presentation of the Lord / Candlemas",
    8: "Lent Begins / Ash Wednesday",
    9: "Palm Sunday",
    10: "Maundy Thursday / Holy Thursday",
    11: "Good Friday",
    12: "Holy Saturday",
    13: "Easter Sunday",
    14: "Divine Mercy Sunday",
    15: "Ascension",
    16: "Pentecost",
    17: "Corpus Christi / Body and Blood of Christ",
    18: "Sacred Heart of Jesus",
    19: "Transfiguration",
    20: "Exaltation of the Holy Cross",
    21: "Christ the King",
    22: "Holy Family",
}

@dataclass
class Holiday:
    number: int
    title: str
    date_2026_text: str = ""
    annual_rule: str = ""
    readings: str = ""
    summary: str = ""
    explanation: str = ""
    image_path: Optional[Path] = None

    @property
    def label(self) -> str:
        return f"{self.number:02d}. {self.title}"

    @property
    def slug(self) -> str:
        return slugify(self.title)

    def long_description_for_calendar(self, event_date: dt.date, notice_days: int) -> str:
        parts = [
            f"{self.label}",
            f"Observed date for this calendar year: {event_date.strftime('%A, %d %B %Y')}",
            f"Reminder notice: {notice_days} days before the event.",
        ]
        if self.date_2026_text:
            parts.append(f"2026 guide date: {self.date_2026_text}")
        if self.annual_rule:
            parts.append(f"Annual/date rule: {self.annual_rule}")
        if self.readings:
            parts.append(f"Suggested NASB 2020 readings: {self.readings}")
        if self.summary:
            parts.append("\nSUMMARY / WHAT IS FITTING:\n" + self.summary)
        if self.explanation:
            parts.append("\nLONG EXPLANATION:\n" + self.explanation)
        if self.image_path:
            parts.append(f"\nBanner image file: {self.image_path.name}")
        parts.append("\nGenerated by Christ Days Calendar Reminder Builder.")
        parts.append(f"Signature: {APP_SIGNATURE}")
        return "\n\n".join(parts)


def app_base_dir() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parent


def find_file(name: str) -> Optional[Path]:
    base = app_base_dir()
    candidates = [
        base / name,
        base / "docs" / name,
        base.parent / name,
        Path.cwd() / name,
        Path.cwd().parent / name,
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


def find_banner_dir() -> Optional[Path]:
    base = app_base_dir()
    folder = "High Res Banners for Days of Christ"
    candidates = [
        base / folder,
        base.parent / folder,
        Path.cwd() / folder,
        Path.cwd().parent / folder,
    ]
    for c in candidates:
        if c.exists() and c.is_dir():
            return c
    return None


def slugify(value: str) -> str:
    value = value.lower().replace("/", " ")
    value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    return value or "event"


def parse_guide(path: Path) -> List[Holiday]:
    text = path.read_text(encoding="utf-8", errors="replace")
    # Match sections beginning with "NN. TITLE" until the next divider.
    pattern = re.compile(r"(?ms)^={20,}\s*\n(\d{2})\.\s*(.+?)\n(.*?)(?=^={20,}\s*\n\d{2}\.\s*|^={20,}\s*\nQUICK DATE INDEX|\Z)")
    holidays: List[Holiday] = []
    for m in pattern.finditer(text):
        num = int(m.group(1))
        title = m.group(2).strip()
        body = m.group(3).strip()
        h = Holiday(number=num, title=title)
        h.date_2026_text = extract_after(body, "2026 date:")
        h.annual_rule = extract_after(body, "Annual rule:")
        h.readings = extract_after(body, "Suggested NASB 2020 readings:")
        h.summary = extract_block(body, "Summary of what is required or fitting:", "Long explanation:")
        h.explanation = extract_block(body, "Long explanation:", None)
        holidays.append(h)
    if not holidays:
        # Fallback: create the expected titles so the app remains usable.
        holidays = [Holiday(number=n, title=t) for n, t in HOLIDAY_TITLES.items()]
    return sorted(holidays, key=lambda h: h.number)


def extract_after(body: str, label: str) -> str:
    for line in body.splitlines():
        if line.startswith(label):
            return line.split(":", 1)[1].strip()
    return ""


def extract_block(body: str, start: str, end: Optional[str]) -> str:
    idx = body.find(start)
    if idx < 0:
        return ""
    idx += len(start)
    if end:
        j = body.find(end, idx)
        block = body[idx:j if j >= 0 else None]
    else:
        block = body[idx:]
    return re.sub(r"\n{3,}", "\n\n", block.strip())


def attach_images(holidays: List[Holiday], banner_dir: Optional[Path]) -> None:
    if not banner_dir:
        return
    files = sorted([p for p in banner_dir.iterdir() if p.suffix.lower() in {".png", ".jpg", ".jpeg"}])
    by_num: Dict[int, Path] = {}
    for p in files:
        m = re.match(r"(\d{2})", p.name)
        if m:
            by_num[int(m.group(1))] = p
    for h in holidays:
        h.image_path = by_num.get(h.number)


def western_easter(year: int) -> dt.date:
    # Meeus/Jones/Butcher Gregorian computus.
    a = year % 19
    b = year // 100
    c = year % 100
    d = b // 4
    e = b % 4
    f = (b + 8) // 25
    g = (b - f + 1) // 3
    h = (19 * a + b - d - g + 15) % 30
    i = c // 4
    k = c % 4
    l = (32 + 2 * e + 2 * i - h - k) % 7
    m = (a + 11 * h + 22 * l) // 451
    month = (h + l - 7 * m + 114) // 31
    day = ((h + l - 7 * m + 114) % 31) + 1
    return dt.date(year, month, day)


def first_sunday_after(date_: dt.date) -> dt.date:
    days = (6 - date_.weekday()) % 7  # Python Monday=0, Sunday=6
    if days == 0:
        days = 7
    return date_ + dt.timedelta(days=days)


def sunday_on_or_before(date_: dt.date) -> dt.date:
    days_since_sunday = (date_.weekday() - 6) % 7
    return date_ - dt.timedelta(days=days_since_sunday)


def advent_start(year: int) -> dt.date:
    christmas = dt.date(year, 12, 25)
    fourth_advent_sunday = sunday_on_or_before(christmas)
    return fourth_advent_sunday - dt.timedelta(days=21)


def holy_family(year: int) -> dt.date:
    christmas = dt.date(year, 12, 25)
    if christmas.weekday() == 6:  # Sunday: many calendars observe Holy Family on Dec 30.
        return dt.date(year, 12, 30)
    return first_sunday_after(christmas)


def event_date_for(number: int, year: int) -> dt.date:
    easter = western_easter(year)
    fixed = {
        2: dt.date(year, 3, 25),
        3: dt.date(year, 12, 25),
        4: dt.date(year, 1, 3),
        5: dt.date(year, 1, 6),
        7: dt.date(year, 2, 2),
        19: dt.date(year, 8, 6),
        20: dt.date(year, 9, 14),
    }
    if number in fixed:
        return fixed[number]
    if number == 1:
        return advent_start(year)
    if number == 6:
        return first_sunday_after(dt.date(year, 1, 6))
    offsets = {
        8: -46,
        9: -7,
        10: -3,
        11: -2,
        12: -1,
        13: 0,
        14: 7,
        15: 39,
        16: 49,
        17: 60,
        18: 68,
    }
    if number in offsets:
        return easter + dt.timedelta(days=offsets[number])
    if number == 21:
        return advent_start(year) - dt.timedelta(days=7)
    if number == 22:
        return holy_family(year)
    raise ValueError(f"Unknown holiday number: {number}")


def ics_escape(value: str) -> str:
    value = value.replace("\\", "\\\\")
    value = value.replace(";", r"\;").replace(",", r"\,")
    value = value.replace("\r\n", "\n").replace("\r", "\n").replace("\n", r"\n")
    return value


def fold_ics_line(line: str) -> str:
    # RFC 5545 uses 75 octets; use a conservative character fold for readable ASCII-heavy content.
    if len(line) <= 74:
        return line
    chunks = []
    while len(line) > 74:
        chunks.append(line[:74])
        line = " " + line[74:]
    chunks.append(line)
    return "\r\n".join(chunks)


def fmt_date(d: dt.date) -> str:
    return d.strftime("%Y%m%d")


def make_uid(h: Holiday, year: int) -> str:
    return f"{EVENT_UID_PREFIX}-{h.number:02d}-{h.slug}-{year}@{EVENT_UID_DOMAIN}"


def make_ics(holidays: List[Holiday], years: Iterable[int], notice_days: int, method: str = "PUBLISH") -> str:
    now = dt.datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "CALSCALE:GREGORIAN",
        f"PRODID:-//{APP_SIGNATURE}//{APP_NAME} {APP_VERSION}//EN",
        f"METHOD:{method}",
        "X-WR-CALNAME:Christ Days Reminders",
        "X-WR-CALDESC:Jesus-centred Christian holiday reminders created by Christ Days Calendar Reminder Builder.",
    ]
    for year in years:
        for h in holidays:
            d = event_date_for(h.number, year)
            end = d + dt.timedelta(days=1)
            title = calendar_summary(h)
            desc = h.long_description_for_calendar(d, notice_days)
            uid = make_uid(h, year)
            lines.extend([
                "BEGIN:VEVENT",
                f"UID:{uid}",
                f"DTSTAMP:{now}",
                f"DTSTART;VALUE=DATE:{fmt_date(d)}",
                f"DTEND;VALUE=DATE:{fmt_date(end)}",
                f"SUMMARY:{ics_escape(title)}",
                f"DESCRIPTION:{ics_escape(desc)}",
                "TRANSP:TRANSPARENT",
                "CATEGORIES:Christ Days,Christian Holiday,NemesisC64,Percarus",
                "X-PERCARUS-CHRIST-DAY:TRUE",
                f"X-PERCARUS-CHRIST-DAY-NO:{h.number:02d}",
            ])
            if h.image_path:
                lines.append(f"X-PERCARUS-BANNER-FILE:{ics_escape(h.image_path.name)}")
            if method.upper() == "CANCEL":
                lines.extend([
                    "STATUS:CANCELLED",
                    "SEQUENCE:2",
                ])
            else:
                lines.extend([
                    "SEQUENCE:1",
                    "BEGIN:VALARM",
                    "ACTION:DISPLAY",
                    f"DESCRIPTION:{ics_escape('Eight-day notice: ' + title)}",
                    f"TRIGGER:-P{int(notice_days)}D",
                    "END:VALARM",
                ])
            lines.append("END:VEVENT")
    lines.append("END:VCALENDAR")
    return "\r\n".join(fold_ics_line(line) for line in lines) + "\r\n"


def calendar_summary(h: Holiday) -> str:
    # Keep titles readable in calendars.
    if "/" in h.title:
        primary, secondary = [part.strip() for part in h.title.split("/", 1)]
        return f"Christ Day: {primary} — {secondary}"
    return f"Christ Day: {h.title}"


class ChristDaysApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title(f"{APP_NAME} v{APP_VERSION}")
        self.geometry("1160x760")
        self.minsize(980, 650)
        self.configure(bg=BG)
        self.style = ttk.Style(self)
        self.configure_styles()

        self.base = app_base_dir()
        self.guide_path = find_file("Jesus_Centred_Christian_Holiday_Guide_2026.txt")
        self.banner_dir = find_banner_dir()
        self.holidays: List[Holiday] = []
        self.selected_index = 0
        self.image_ref = None

        self.platform_var = tk.StringVar(value="Google Calendar / ICS")
        self.start_year_var = tk.IntVar(value=DEFAULT_START_YEAR)
        self.end_year_var = tk.IntVar(value=DEFAULT_END_YEAR)
        self.notice_days_var = tk.IntVar(value=DEFAULT_NOTICE_DAYS)

        self.load_assets()
        self.build_ui()
        self.populate_list()
        self.select_index(0)

    def configure_styles(self) -> None:
        try:
            self.style.theme_use("clam")
        except tk.TclError:
            pass
        self.style.configure("TFrame", background=BG)
        self.style.configure("Panel.TFrame", background=PANEL)
        self.style.configure("TLabel", background=BG, foreground=TEXT, font=("Segoe UI", 10))
        self.style.configure("Muted.TLabel", background=BG, foreground=MUTED, font=("Segoe UI", 9))
        self.style.configure("Title.TLabel", background=BG, foreground=SOFT_GOLD, font=("Georgia", 20, "bold"))
        self.style.configure("Gold.TButton", font=("Segoe UI", 10, "bold"), padding=8)
        self.style.map("Gold.TButton", foreground=[("active", BG)], background=[("active", SOFT_GOLD)])
        self.style.configure("TRadiobutton", background=PANEL, foreground=TEXT, font=("Segoe UI", 10))
        self.style.configure("TCheckbutton", background=PANEL, foreground=TEXT)
        self.style.configure("TEntry", fieldbackground="#fdf6e3")

    def load_assets(self) -> None:
        if self.guide_path and self.guide_path.exists():
            self.holidays = parse_guide(self.guide_path)
        else:
            self.holidays = [Holiday(number=n, title=t) for n, t in HOLIDAY_TITLES.items()]
        attach_images(self.holidays, self.banner_dir)

    def build_ui(self) -> None:
        header = tk.Frame(self, bg=BG)
        header.pack(fill="x", padx=18, pady=(16, 8))
        tk.Label(header, text=APP_NAME, bg=BG, fg=SOFT_GOLD, font=("Georgia", 22, "bold")).pack(anchor="w")
        tk.Label(header, text=f"Version {APP_VERSION} — {APP_DATE} • {APP_SIGNATURE}", bg=BG, fg=MUTED, font=("Segoe UI", 10)).pack(anchor="w", pady=(2, 0))

        main = tk.Frame(self, bg=BG)
        main.pack(fill="both", expand=True, padx=18, pady=10)

        left = tk.Frame(main, bg=PANEL, bd=1, relief="solid")
        left.pack(side="left", fill="y", padx=(0, 12))
        left.configure(width=330)
        left.pack_propagate(False)

        tk.Label(left, text="Calendar Target", bg=PANEL, fg=SOFT_GOLD, font=("Georgia", 14, "bold")).pack(anchor="w", padx=14, pady=(14, 6))
        platforms = ["Google Calendar / ICS", "Microsoft Outlook / ICS", "Apple Calendar / ICS", "Linux Calendar / ICS"]
        for p in platforms:
            tk.Radiobutton(left, text=p, variable=self.platform_var, value=p, bg=PANEL, fg=TEXT, selectcolor=PANEL2, activebackground=PANEL, activeforeground=SOFT_GOLD, font=("Segoe UI", 10), command=self.update_platform_notes).pack(anchor="w", padx=18, pady=2)

        opts = tk.Frame(left, bg=PANEL)
        opts.pack(fill="x", padx=14, pady=(14, 4))
        tk.Label(opts, text="Year range", bg=PANEL, fg=SOFT_GOLD, font=("Segoe UI", 10, "bold")).grid(row=0, column=0, columnspan=4, sticky="w")
        tk.Label(opts, text="From", bg=PANEL, fg=TEXT).grid(row=1, column=0, pady=6, sticky="e")
        tk.Entry(opts, textvariable=self.start_year_var, width=7, bg="#fff7df").grid(row=1, column=1, padx=6)
        tk.Label(opts, text="To", bg=PANEL, fg=TEXT).grid(row=1, column=2, sticky="e")
        tk.Entry(opts, textvariable=self.end_year_var, width=7, bg="#fff7df").grid(row=1, column=3, padx=6)
        tk.Label(opts, text="Notice days", bg=PANEL, fg=TEXT).grid(row=2, column=0, columnspan=2, pady=6, sticky="w")
        tk.Entry(opts, textvariable=self.notice_days_var, width=7, bg="#fff7df").grid(row=2, column=2, padx=6, sticky="w")

        tk.Button(left, text="Create ADD Reminder .ics", command=self.export_add, bg=GOLD, fg="#111111", activebackground=SOFT_GOLD, font=("Segoe UI", 10, "bold"), relief="flat", padx=8, pady=8).pack(fill="x", padx=14, pady=(14, 6))
        tk.Button(left, text="Create REMOVE/CANCEL .ics", command=self.export_remove, bg="#3b2d1b", fg=SOFT_GOLD, activebackground="#4b3921", font=("Segoe UI", 10, "bold"), relief="flat", padx=8, pady=8).pack(fill="x", padx=14, pady=6)
        tk.Button(left, text="Open Exports Folder", command=self.open_exports, bg=PANEL2, fg=TEXT, activebackground="#242b3c", font=("Segoe UI", 10), relief="flat", padx=8, pady=8).pack(fill="x", padx=14, pady=6)
        tk.Button(left, text="Login / API Notes", command=self.show_login_notes, bg=PANEL2, fg=TEXT, activebackground="#242b3c", font=("Segoe UI", 10), relief="flat", padx=8, pady=8).pack(fill="x", padx=14, pady=6)
        tk.Button(left, text="Help", command=self.show_help, bg=PANEL2, fg=TEXT, activebackground="#242b3c", font=("Segoe UI", 10), relief="flat", padx=8, pady=8).pack(fill="x", padx=14, pady=6)
        tk.Button(left, text="About", command=self.show_about, bg=PANEL2, fg=TEXT, activebackground="#242b3c", font=("Segoe UI", 10), relief="flat", padx=8, pady=8).pack(fill="x", padx=14, pady=6)

        self.platform_notes = tk.Text(left, height=10, bg="#0c1018", fg=MUTED, wrap="word", relief="flat", padx=8, pady=8, font=("Segoe UI", 9))
        self.platform_notes.pack(fill="both", expand=True, padx=14, pady=(12, 14))
        self.platform_notes.configure(state="disabled")
        self.update_platform_notes()

        center = tk.Frame(main, bg=BG)
        center.pack(side="left", fill="both", expand=True)

        top = tk.Frame(center, bg=BG)
        top.pack(fill="both", expand=False)
        list_frame = tk.Frame(top, bg=PANEL, bd=1, relief="solid")
        list_frame.pack(side="left", fill="y", padx=(0, 12))
        tk.Label(list_frame, text="Christ-Centred Days", bg=PANEL, fg=SOFT_GOLD, font=("Georgia", 13, "bold")).pack(anchor="w", padx=10, pady=(10, 4))
        self.listbox = tk.Listbox(list_frame, width=38, height=24, bg="#0d111a", fg=TEXT, selectbackground="#4a3920", selectforeground=SOFT_GOLD, activestyle="none", borderwidth=0, highlightthickness=0, font=("Segoe UI", 10))
        self.listbox.pack(fill="y", padx=10, pady=(0, 10))
        self.listbox.bind("<<ListboxSelect>>", self.on_select)

        preview_frame = tk.Frame(top, bg=PANEL, bd=1, relief="solid")
        preview_frame.pack(side="left", fill="both", expand=True)
        tk.Label(preview_frame, text="Banner Preview", bg=PANEL, fg=SOFT_GOLD, font=("Georgia", 13, "bold")).pack(anchor="w", padx=12, pady=(10, 4))
        self.image_label = tk.Label(preview_frame, text="No banner found.", bg="#0d111a", fg=MUTED, font=("Segoe UI", 11), anchor="center")
        self.image_label.pack(fill="both", expand=True, padx=12, pady=(0, 12))

        details_frame = tk.Frame(center, bg=PANEL, bd=1, relief="solid")
        details_frame.pack(fill="both", expand=True, pady=(12, 0))
        tk.Label(details_frame, text="Event Details from Guide", bg=PANEL, fg=SOFT_GOLD, font=("Georgia", 13, "bold")).pack(anchor="w", padx=12, pady=(10, 4))
        self.details = tk.Text(details_frame, bg="#0d111a", fg=TEXT, insertbackground=TEXT, wrap="word", relief="flat", padx=14, pady=12, font=("Segoe UI", 10), height=12)
        self.details.pack(fill="both", expand=True, padx=12, pady=(0, 12))
        self.details.configure(state="disabled")

    def populate_list(self) -> None:
        self.listbox.delete(0, tk.END)
        for h in self.holidays:
            self.listbox.insert(tk.END, h.label)

    def on_select(self, _event=None) -> None:
        sel = self.listbox.curselection()
        if sel:
            self.select_index(sel[0])

    def select_index(self, index: int) -> None:
        if not self.holidays:
            return
        index = max(0, min(index, len(self.holidays) - 1))
        self.selected_index = index
        self.listbox.selection_clear(0, tk.END)
        self.listbox.selection_set(index)
        self.listbox.activate(index)
        h = self.holidays[index]
        self.update_details(h)
        self.update_image(h)

    def update_details(self, h: Holiday) -> None:
        text = [h.label]
        if h.date_2026_text:
            text.append(f"\n2026 date: {h.date_2026_text}")
        if h.annual_rule:
            text.append(f"Annual rule: {h.annual_rule}")
        if h.readings:
            text.append(f"Suggested NASB 2020 readings: {h.readings}")
        if h.summary:
            text.append("\nSUMMARY / WHAT IS FITTING:\n" + h.summary)
        if h.explanation:
            text.append("\nLONG EXPLANATION:\n" + h.explanation)
        if h.image_path:
            text.append(f"\nBanner: {h.image_path}")
        self.details.configure(state="normal")
        self.details.delete("1.0", tk.END)
        self.details.insert("1.0", "\n".join(text))
        self.details.configure(state="disabled")

    def update_image(self, h: Holiday) -> None:
        if not h.image_path or not h.image_path.exists():
            self.image_label.configure(image="", text="No banner found.")
            self.image_ref = None
            return
        try:
            img = tk.PhotoImage(file=str(h.image_path))
            max_w = 690
            max_h = 280
            factor = max(1, math.ceil(max(img.width() / max_w, img.height() / max_h)))
            if factor > 1:
                img = img.subsample(factor, factor)
            self.image_ref = img
            self.image_label.configure(image=img, text="")
        except Exception as exc:
            self.image_label.configure(image="", text=f"Could not load banner preview:\n{exc}")
            self.image_ref = None

    def year_range(self) -> List[int]:
        try:
            start = int(self.start_year_var.get())
            end = int(self.end_year_var.get())
            notice = int(self.notice_days_var.get())
        except Exception:
            raise ValueError("Year range and notice days must be whole numbers.")
        if start < 1900 or end > 2100:
            raise ValueError("Please use years between 1900 and 2100.")
        if end < start:
            raise ValueError("End year must be the same as or later than start year.")
        if notice < 0 or notice > 365:
            raise ValueError("Notice days should be between 0 and 365.")
        if (end - start + 1) > 80:
            raise ValueError("Please keep the export at 80 years or fewer at a time.")
        return list(range(start, end + 1))

    def export_add(self) -> None:
        self.export_ics("PUBLISH")

    def export_remove(self) -> None:
        msg = (
            "This creates a cancellation .ics using the exact unique UIDs produced by this app.\n\n"
            "Most calendar systems should target only those generated events, but not every calendar app honors imported cancellation files equally.\n\n"
            "The safest method is to import the ADD file into a separate calendar named 'Christ Days Reminders', then delete that calendar if needed.\n\n"
            "Create the REMOVE/CANCEL file now?"
        )
        if messagebox.askyesno("Create remove/cancel file", msg):
            self.export_ics("CANCEL")

    def export_ics(self, method: str) -> None:
        try:
            years = self.year_range()
            notice = int(self.notice_days_var.get())
            ics = make_ics(self.holidays, years, notice, method=method)
            export_dir = self.base / "exports"
            export_dir.mkdir(parents=True, exist_ok=True)
            platform_slug = slugify(self.platform_var.get())
            suffix = "ADD" if method.upper() != "CANCEL" else "REMOVE_CANCEL"
            path = export_dir / f"Christ_Days_Reminders_{suffix}_{years[0]}-{years[-1]}_{platform_slug}.ics"
            path.write_text(ics, encoding="utf-8", newline="")
            self.write_manifest(path, years, notice, method)
            messagebox.showinfo("ICS created", f"Created:\n{path}\n\nImport this file into {self.platform_var.get()}.")
        except Exception as exc:
            messagebox.showerror("Export failed", str(exc))

    def write_manifest(self, ics_path: Path, years: List[int], notice: int, method: str) -> None:
        manifest = {
            "app": APP_NAME,
            "version": APP_VERSION,
            "created_utc": dt.datetime.utcnow().isoformat(timespec="seconds") + "Z",
            "method": method,
            "calendar_target": self.platform_var.get(),
            "notice_days": notice,
            "start_year": years[0],
            "end_year": years[-1],
            "ics_file": str(ics_path),
            "uid_prefix": EVENT_UID_PREFIX,
            "uid_domain": EVENT_UID_DOMAIN,
            "events": [
                {"number": h.number, "title": h.title, "year": y, "date": event_date_for(h.number, y).isoformat(), "uid": make_uid(h, y)}
                for y in years for h in self.holidays
            ],
        }
        manifest_path = ics_path.with_suffix(".manifest.json")
        manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    def open_exports(self) -> None:
        export_dir = self.base / "exports"
        export_dir.mkdir(parents=True, exist_ok=True)
        try:
            if sys.platform.startswith("win"):
                os.startfile(export_dir)  # type: ignore[attr-defined]
            elif sys.platform == "darwin":
                subprocess.Popen(["open", str(export_dir)])
            else:
                subprocess.Popen(["xdg-open", str(export_dir)])
        except Exception as exc:
            messagebox.showerror("Could not open folder", str(exc))

    def set_note(self, text: str) -> None:
        self.platform_notes.configure(state="normal")
        self.platform_notes.delete("1.0", tk.END)
        self.platform_notes.insert("1.0", text)
        self.platform_notes.configure(state="disabled")

    def update_platform_notes(self) -> None:
        p = self.platform_var.get()
        if "Google" in p:
            note = "Google Calendar: import the ADD .ics file into a chosen calendar. For safe removal, use a separate calendar or import the REMOVE/CANCEL file if your Google setup honors cancellations. Live API login requires your own Google OAuth desktop-app client ID."
        elif "Microsoft" in p:
            note = "Microsoft Outlook / Microsoft 365: import the ADD .ics file. API-based create/delete can be added later through Microsoft Graph with Calendars.ReadWrite permissions and your Azure app registration."
        elif "Apple" in p:
            note = "Apple Calendar: import the .ics file into a new calendar, preferably named Christ Days Reminders. Removing the whole imported set is safest if it is isolated in its own calendar."
        else:
            note = "Linux calendars: GNOME Calendar, Evolution, KOrganizer, Thunderbird, and many other apps can import .ics files. Use a separate calendar if available for safest removal."
        self.set_note(textwrap.fill(note, 42))

    def show_login_notes(self) -> None:
        text = (
            "LIVE LOGIN / API NOTES\n\n"
            "This offline build intentionally does not ask for or store passwords. Proper Google or Microsoft calendar login must use OAuth, which requires developer credentials registered to your own Google Cloud or Microsoft Entra/Azure app.\n\n"
            "The ready-to-use mode in this package is .ics export/import, which works broadly across Google, Outlook/Microsoft, Apple Calendar, and common Linux calendar apps.\n\n"
            "Deletion safety is handled by app-generated UIDs and by recommending a separate calendar named 'Christ Days Reminders'. API-based deletion can later delete only the event IDs created and stored by this app."
        )
        messagebox.showinfo("Login / API Notes", text)

    def show_help(self) -> None:
        text = (
            "HELP\n\n"
            "1. Choose the calendar target.\n"
            "2. Choose the year range. Default is 2026–2040. Moveable feasts such as Easter, Ascension, Pentecost, Corpus Christi, Sacred Heart, and Christ the King are calculated for each year.\n"
            "3. Keep notice days at 8, or change it.\n"
            "4. Click 'Create ADD Reminder .ics'.\n"
            "5. Import that .ics into your calendar app.\n\n"
            "Removal:\n"
            "Use 'Create REMOVE/CANCEL .ics' for the same year range. The cancellation file uses matching UIDs, so it is designed to affect only events created by this app. Because calendar apps differ, the safest method is to import reminders into their own separate calendar and delete that calendar if needed.\n\n"
            "Images:\n"
            "The app previews the numbered banners from 'High Res Banners for Days of Christ'. Calendar event descriptions mention the banner filename, but most calendar systems do not reliably embed large local images inside events."
        )
        messagebox.showinfo("Help", text)

    def show_about(self) -> None:
        text = (
            f"{APP_NAME}\n"
            f"Version {APP_VERSION} — {APP_DATE}\n\n"
            "Purpose: Generate Christ-centred Christian holiday calendar reminders using the prepared guide and banners.\n\n"
            f"Signature / mark:\n{APP_SIGNATURE}\n\n"
            "Built as a compact desktop helper with safety-conscious UID tagging, .ics export, cancellation-file generation, guide parsing, banner preview, and future API extension points."
        )
        messagebox.showinfo("About", text)


def main() -> None:
    app = ChristDaysApp()
    app.mainloop()


if __name__ == "__main__":
    main()
